#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           arm_right,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           top_left,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           claw_grab,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           bottom_left,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           side_wheel,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           top_right,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           claw_tilt,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           bottom_right,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           claw_slide,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          arm_left,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

// this file is seperate so i can open it in np++

//   drive train:
//     [5] [7]
//
//     [4] [6]
//   motors:
//     1 )
//     2 )
//     3 ) side wheel
//     4 ) bottom left
//     5 ) top left
//     6 ) bottom right
//     7 ) top right
//     8 )
//     9 )
//     10)
//   analog:
//     1)
//     2)
//     3)
//     4)
//     5)
//     6)
//     7)
//     8)
//   digital:
//     1 ) left encoder (top wire)
//     2 ) left encoder (bottom wire)
//     3 )
//     4 )
//     5 )
//     6 )
//     7 )
//     8 ) right encoder (top wire)
//     9 ) right encoder (bottom wire)
//     10)
//     11) ultrasonic (input)
//     12) ultrasonic (output)
//   UART:
//     1)
//     2) LCD display
//   I2C:
//

#define uint32_t unsigned int

#include "code.c"
