#pragma config(UART_Usage, UART1, uartUserControl, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void send(unsigned char x) {
	sendChar(UART1,x);
}

unsigned char get() {
	while (true) {
		int out=getChar(UART2);
		if (out!=-1) {
			writeDebugStream("%c",out);
			return out;
		}
	}
}

task receive() {
	while (true) {
		get();
	}
	while (true) {
		unsigned char checksum=0;
		if (get()!=0xaa)
			continue;
		if (get()!=0x55)
			continue;
		unsigned char packetType=get();
		unsigned char numBytes=get();
		unsigned char data[256];
		for (int curByte=0;curByte<numBytes;curByte++) {
			int bt=get();
			data[curByte]=bt;
			checksum+=bt;
		}
		for (int curByte=0;curByte<numBytes;curByte++) {
			//writeDebugStream(" %02x",data[curByte]);
		}
		if (checksum==0) {
			writeDebugStreamLine(" valid type %02x size %02x ",packetType,numBytes);
			switch (packetType) {
				case 0x1e:
					send(0xaa); send(0x55); send(0x16); send(0x02);
					send(0x01); send(0xFF);
				break;
			}
		} else {
			writeDebugStreamLine(" inv %i alid type %02x size %02x",checksum,packetType,numBytes);
		}
	}
}

unsigned char derp[44]={
	0xaa,0x55,0x1e,0x12,0x02,0x20,0x20,0x20,0x20,0x75,0x62,0x72,0x74,0x74,0x65,0x73,0x74,0x20,0x20,0x20,0x20,0x81,
	0xaa,0x55,0x1e,0x12,0x03,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0x20,0xfd
};

unsigned char data[16]={
	32,32,32,32,76,73,84,76,32,66,73,67,72,32,32,32
};

task main() {
	startTask(receive);
	while (true) {
		sendChar(UART2,68);
		sendChar(UART2,69);
		sendChar(UART2,82);
		sendChar(UART2,80);
		wait1Msec(2000);
	}
	unsigned char sum=256-3;
	for (int i=0;i<16;i++) {
		sum-=data[i];
	}
	writeDebugStreamLine("CHECKSUM %i",sum);
	//checksum=255-(checksum%256);
	while (true) {
		sendChar(UART1,0xaa);
		sendChar(UART1,0x55);
		sendChar(UART1,0x1e);
		sendChar(UART1,0x12);
		sendChar(UART1,0x03);
		for (int i=0;i<16;i++) {
			sendChar(UART1,data[i]);
		}
		sendChar(UART1,sum);
		wait1Msec(100);
	}
}
